version: 2.1
orbs:
  node: circleci/node@2.0.1
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
#      - aws-s3/sync:
#          arguments: |
#            --acl public-read \
#            --cache-control "max-age=86400"
#          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
#          aws-region: AWS_REGION_BLUE
#          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
#          from: bucket
#          overwrite: true
#          to: 's3://my-s3-bucket-name/prefix'
#      - aws-s3/copy:
#          arguments: '--dry-run'
#          from: bucket/build_asset.txt
#          to: 's3://my-s3-bucket-name'
workflows:
  test-and-deploy:
    jobs:
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
      - lint
